name: Build and Release Binaries

# This workflow is now triggered manually from the Actions tab
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        # Using the stable .NET 8 SDK for reliability
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Publish Linux x64
      run: dotnet publish -c Release --framework net8.0-desktop --self-contained true -r linux-x64 -o release/linux-x64

    - name: Build and Publish Linux arm64
      run: dotnet publish -c Release --framework net8.0-desktop --self-contained true -r linux-arm64 -o release/linux-arm64

    - name: Upload Linux Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-linux
        path: release/

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Publish Windows x64
      run: dotnet publish -c Release --framework net8.0-windows10.0.19041 --self-contained true -r win-x64 -o release/win-x64

    - name: Build and Publish Windows arm64
      run: dotnet publish -c Release --framework net8.0-windows10.0.19041 --self-contained true -r win-arm64 -o release/win-arm64

    - name: Upload Windows Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-windows
        path: release/